<a href="https://colab.research.google.com/github/Lara-mt/MAT-422/blob/main/MAT422_HW1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

MAT 422 HW 1.2
Math concepts
1. Linear Spaces
2. Orthogonality
3. Gram Schmidt Process
4. Eigenvalues and Eigenvectors

1.2.1 Linear Spaces
A vector space is a set of vectors that is closed under vector addition and scalar multiplication.

This means that if two vectors belong to the same vector space, their sum must also belong to the space as well as scalar multiplication.

In [250]:
import numpy as np
## Vector addition and scalar multiplication
## Going to show that adding vectors or multiplying scalars remain in R^3


u = np.array([1,2,3])
v = np.array([4,-1,2])
c = 3

vector_sum = u + v
scalar_multiple = c * u

print("u = ",u)
print("v = ",v)
print("u + v =", vector_sum)
print("3u =", scalar_multiple)

u =  [1 2 3]
v =  [ 4 -1  2]
u + v = [5 1 5]
3u = [3 6 9]


The results are vectors in the same space R^3.


In [251]:
## Zero vector
## A Vector space contains the zero vector, adding this to a vector
## does not change the vector

zero = np.array([0,0,0])

print("u + 0 = ", u + zero)
print(" u =", u)




u + 0 =  [1 2 3]
 u = [1 2 3]


Adding the zero vector to vector u gives u again.

In [252]:
## Additive Inverse
## Every vector has an additive inverse. A vector added
## to its inverse gives the zero vector.

neg_u = -u
print(" -u =", neg_u)
print("u + (-u) =", u + neg_u)

 -u = [-1 -2 -3]
u + (-u) = [0 0 0]


The vector "-u" is the additive inverse of u because their sum is the zero vector.

In [253]:
## Linear Combination and Span
## A linear combination is formed by multiplying vectors
## by scalars and adding the results.

w = 2 * u - v
print("w = 2u - v ", w)

w = 2u - v  [-2  5  4]


The vector w is a linear combination of u and v. Therefore, w belongs to the span of u and v.

1.2.2 Orthogonality

Two vectors are orthogonal if their dot product is equal to zero.

for vectors u and v:

u dot v = 0

Orthogonal vectors meet at a 90 degree angle.

In [254]:
## Dot product

u = np.array([1,2])
v = np.array([2,-1])

print("u =", u)
print("v =", v)

dot_product = np.dot(u,v)
print("u dot v = ", dot_product)

u = [1 2]
v = [ 2 -1]
u dot v =  0


In [255]:
## Geometric interpretation
## Norm and angle between vectors

## Norm represents vectors length
## Angle between vectors can be found using
## cos(theta) = (u * v) / (||u|| ||v||)


#norm
norm_u = np.linalg.norm(u)
norm_v = np.linalg.norm(v)

print("||u|| =", norm_u)
print("||v|| =", norm_v)

||u|| = 2.23606797749979
||v|| = 2.23606797749979


In [256]:
## Angle between vectors
cos_theta = dot_product / (norm_u * norm_v)

theta = np.arccos(cos_theta)
theta_degrees = np.degrees(theta)

print("cos(theta) =", cos_theta)
print("theta = ", theta_degrees, "degrees")

cos(theta) = 0.0
theta =  90.0 degrees


The angle is 90 degrees so they are orthogonal

In [257]:
## Projection
## The projection of u onto v measures how much of
## u points in the direction of v

projection = (np.dot(u,v) / np.dot(v,v)) * v
print("Projection of u onto v = ", projection)

Projection of u onto v =  [ 0. -0.]


The projection is the zero vector because u and v are orthogonal. Neither vector has a component in the direction of the other.

The projection produced an output of -0, it should be 0 but it produced a number so small because of floating point roundoff.

In [258]:
## Gram-Scmidt Process
## This process takes linearly independent vectors
## and converts them into an orthonormal set

## It works by removing the projection of one vector onto
## another then normalizig the result

v1 = np.array([1.0,1.0])
v2 = np.array([1.0,0.0])

Step 1: First vector is kept as the first orthogonal vector

In [259]:
u1 = v1
print("u1 =", u1)

u1 = [1. 1.]


Step 2: Remove the projection to make the second vector orthogonal to the first, subtract the projection of v2 onto u1.

In [260]:
projection = (np.dot(v2,u1)/ np.dot(u1,u1))* u1

u2 = v2 - projection

print("Projection of v2 onto u1 =",projection)
print("u2 =", u2)

Projection of v2 onto u1 = [0.5 0.5]
u2 = [ 0.5 -0.5]


If u1 and u2 are orthogonal then dot product should be zero

In [261]:
print("u1 dot u2 =", np.dot(u1,u2))

u1 dot u2 = 0.0


Now to normalize the vectors to get them to be length = 1

In [262]:
q1 = u1 / np.linalg.norm(u1)
q2 = u2 / np.linalg.norm(u2)

print("q1 =", q1)
print("q2 =", q2)

q1 = [0.70710678 0.70710678]
q2 = [ 0.70710678 -0.70710678]


In [263]:
print("||q1|| = ", np.linalg.norm(q1))
print("||q2|| = ", np.linalg.norm(q2))

||q1|| =  0.9999999999999999
||q2|| =  0.9999999999999999


Norm is basically 1

In [264]:
# Verifying result
Q = np.column_stack((q1,q2))

print("Q =")
print(Q)

print("\nQ.T @ Q =")
print(Q.T @ Q)

Q =
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]

Q.T @ Q =
[[ 1.00000000e+00 -2.23711432e-17]
 [-2.23711432e-17  1.00000000e+00]]


The -2 diagonal entries are basically zero so we have the identity matrix.

1.2.4 Eigenvalues and Eigenvectors

An eigenvector is a direction that a matrix changes only by scaling.

For a matrix A, an eigenvector v and eigenvalue lamba satisfy:

A * v = lamba * v

In [265]:
A = np.array ([
    [2,1],
    [1,2]
])

print("A =")
print(A)

A =
[[2 1]
 [1 2]]


In [266]:
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[3. 1.]

Eigenvectors:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


To verify an eigenvector and eigenvalue, I will check whether multiplying the eigenvector by A gives the same result as multiplying the eigenvector by its eigenvalue.

In [267]:
lam = eigenvalues[0]
v = eigenvectors[:,0]

Av = A @ v
lambda_v = lam * v

print("lambda = ", lam)
print("v = ", v)

print("\nA @ v =", Av)
print("lambda * v =", lambda_v)

lambda =  3.0
v =  [0.70710678 0.70710678]

A @ v = [2.12132034 2.12132034]
lambda * v = [2.12132034 2.12132034]


In [268]:
#Residual Norm
residual = Av - lambda_v
residual_norm = np.linalg.norm(residual)

print("Residual =", residual)
print("Residual norm =", residual_norm)

Residual = [0. 0.]
Residual norm = 0.0


The residual norm is approximately 0, which confirms that A @ v is equal to lambda * v. Therefore, v is an eigenvector of A with eigenvalue lambda.

In [269]:
v1 = eigenvectors[:,0]
v2 = eigenvectors[:,1]
print("Dot product of eigenvectors = ", np.dot(v1,v2))

Dot product of eigenvectors =  0.0


Because A is a symmetric matrix, its eigenvectors are orthogonal. Their dot product is approx 0, confirming this property.

The eigenvectors represent directions that remain unchanged in direction when A is applied, while the eigenvalues represent how much those directions are scaled.

